---
name: ${SNAP_NAME}
version: '0.1'
summary: python test package
description: |
  test app for python
base: core20
grade: devel
confinement: strict
architectures:
  - build-on: ${SNAP_ARCH}
    run-on: ${SNAP_ARCH}

apps:
  ${SNAP_NAME}:
    command: bin/app
    daemon: simple
    plugs:
      - home
      - network-bind
      - framebuffer
    environment:
      # daemons execute as root so the python paths must be updated
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$PYTHONPATH

parts:
  app:
    plugin: python
    source: .
    # fix for sys.path not including dist-packages for wheel
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages:$PYTHONPATH
    stage-packages:  # packages required for part to run (with python plugin)
      - python3-wheel
      - ncbi-blast+
