name: ${SNAP_NAME}
version: '0.1'
summary: python test package
description: |
 test app for python
base: core20
grade: devel
confinement: strict
architectures:
  - build-on: ${ARCH}
    run-on: ${ARCH}

apps:
  testapp:
    command: bin/hello
    daemon: simple
    plugs: 
      - home
      - network-bind
    environment:
      # daemons execute as root so the python paths must be updated
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$PYTHONPATH
  # executed with testapp.testcli or more generally <SNAP_NAME>.<CLI_CMD>
  testcli: 
    command: bin/hello
    plugs: 
      - home
      - network-bind
  # executed with testapp.version or more generally <SNAP_NAME>.<CLI_CMD>
  version: 
    command: bin/vers
    plugs: 
      - home
      - network-bind

parts:
  testapp:
    plugin: python
    source: .
    # fix for sys.path not including dist-packages for wheel
    build-environment:
      - PYTHONPATH: $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages:$PYTHONPATH
    stage-packages: # packages required for part to run (with python plugin)
      - python3-wheel
      - ncbi-blast+
    
