name: testapp
version: '0.1'
#version-script: git describe --abbrev=1 --tags
summary: python test package
description: |
 test app for python
base: core20
grade: stable
confinement: strict

apps:
  testapp:
    command: bin/hello
    plugs: 
      - home
      - network-bind
parts:
  testapp:
    plugin: python
    source: .
    # fix for sys.path not including dist-packages for wheel
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    stage-packages: # packages required for part to run (with python plugin)
      - python3-wheel
      - ncbi-blast+
    
