name: testapp
version: '0.1'
#version-script: git describe --abbrev=1 --tags
summary: python test package
description: |
 test app for python
architectures:
     - build-on: arm64
       run-on: arm64
base: core20
grade: stable
confinement: strict

apps:
  testapp:
    command: bin/hello
    plugs: 
      - home
      - network-bind
parts:
  testapp:
    plugin: python
    source: .
    stage-packages: 
      - ncbi-blast+
      - python3
