name: testapp
version: '0.1'
summary: python test package
description: |
 test app for python
base: core20
grade: devel
confinement: strict

apps:
  testapp:
    command: bin/hello
    plugs: 
      - home
      - network-bind

parts:
  testapp:
    plugin: python
    source: .
    # fix for sys.path not including dist-packages for wheel
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages:$PYTHONPATH"
    stage-packages: # packages required for part to run (with python plugin)
      - python3-wheel
      - ncbi-blast+
    
